### ISSUE TITLE
ibus-rime配置的一些问题

### ISSUE THREAD

**Issue by bickman** [rime/ibus-rime#101]
我的系统是manjaro 20.0.3 Gnome.
ibus-rime的主题（颜色，字体）需要到gnome-shell里面配置，候选词的个数需要到default.custom.yaml里配置，然后水平或者竖直显示又需要新建立一个ibus-rime.yaml再配置，感觉非常乱，能否统一一个地方进行配置呢？

**Comment by lotem** [comment]
ibus-rime只實現了部分上述功能，無法通過配置修改其他軟件實現的功能。
