### ISSUE TITLE
Allow installing using CMake

### ISSUE THREAD

**Issue by jtojnar** [rime/ibus-rime#108]
Currently we are building this as

```
cmake <cmake flags> build # configure
cd build
make
cd ..
make install PREFIX=...
```

since `install.sh` or the top-level Makefile is not flexible enough for us.

Would it be possible to add `install` target to `CMakeLists.txt`? Then we could use the CMake-generated `Makefile` for both building and installation.

There would be an added benefit that it would concentrate all build and installation instructions in `CMakeLists.txt` and the top-level `Makefile` could just redirect the `install` target to the `build/` directory like it [already does with build](https://github.com/rime/ibus-rime/blob/33b2755fbdacfad00fb1edec97174c55e04f748f/Makefile#L15).

**Comment by lotem** [comment]
`install.sh` is just for my own convenience while developing. I'll remove it.
