### ISSUE TITLE
fcitx-rime的菜单图标要怎么修改或替换？

### ISSUE THREAD

**Issue by windonsky** [rime/ibus-rime#113]
安装的deepin20，fcitx-rime切换到rime后，rime的那个ㄓ图标又小又模糊，我想着自己做个大的替换掉，但是看了源代码的data里的图形文件，并没有这个状态图标。
对以下的疑似ㄓ图标文件替换过皆未达到目标：
```
/usr/share/fcitx/imicon/
/usr/share/icons/hicolor/48x48/apps/
/usr/share/icons/hicolor/scalable/status/
/usr/share/icons/hicolor/128x128/apps/
```
![2020-12-09_23-40](https://user-images.githubusercontent.com/11811250/101651339-ead0be00-3a77-11eb-9c08-d8aa89ba3ebd.png)

**Comment by lotem** [comment]
fcitx-rime 是另一款软件

**Comment by windonsky** [comment]
> fcitx-rime 是另一款软件

fcitx-rime仓库没有开放issues，只好借地一用。

**Comment by lotem** [comment]
不必。fcitx團隊不會來這兒看問題的。
