### ISSUE TITLE
请问如何备份「用户词典」？

### ISSUE THREAD

**Issue by linpxin** [rime/ibus-rime#114]
执行
pkill  ibus-daemon
rime_dict_manager  -e luna_pinyin  export.txt
后提示 “error opening db 'luna_pinyin.userdb' read-only”

**Comment by lotem** [comment]
估計是輸入第二行命令的時候又啓動了ibus。
須一次連續執行以上兩行命令。
或者用輸入法菜單裏的同步菜單項把詞典快照輸出到 `$HOME/.config/ibus/rime/sync`

**Comment by linpxin** [comment]
用「同步」可以输出词典快照

**Comment by linpxin** [comment]
执行
pkill  ibus-daemon
rime_dict_manager  -i  luna_pinyin  bak_from_windows.txt
ibus_daemon&
尽管提示「import  3230 entries」，但实际上根本没有导入(通过「同步」再次输出词典快照，发现确实没有导入)

请问除了rime_dict_manager，还有他恢复词典快照的方法吗？

操作系统是Ubuntu 20.04.1LTS，内核版本5.4.0
