### ISSUE TITLE
在Google Doc上无法显示拼音选项

### ISSUE THREAD

**Issue by desdevol** [rime/ibus-rime#116]
目前只在Google Doc上发现此问题，在Google Sheet上并没发现相同问题。
在系统 Manjaro 20 Gnome版本上进行。

**Comment by foxB612** [comment]
相同问题，Google Doc中不显示候选框，但可以盲选、输入。
测试过ibus-pinyin正常，因此大概可以排除ibus框架的问题。
OS: Ubuntu 20.04
ibus-rime: 1.4.0-2，由Ubuntu apt安装

**Comment by foxB612** [comment]
> 相同问题，Google Doc中不显示候选框，但可以盲选、输入。
> 测试过ibus-pinyin正常，因此大概可以排除ibus框架的问题。
> OS: Ubuntu 20.04
> ibus-rime: 1.4.0-2，由Ubuntu apt安装

[rime/squirrel # 345](https://github.com/rime/squirrel/issues/345#issuecomment-737401488) 使用这个方法已解决。
