### ISSUE TITLE
default.custom.yaml 沒效，default.yaml 也被 overwrite

### ISSUE THREAD

**Issue by lkblkb** [rime/ibus-rime#119]
我遇到兩個問題：

1. 我的 default.custom.yaml  一直被忽略，裡面的設定無效
2. 如果強制把 default.custom.yaml 寫到 .config/ibus/rime/build
default.yaml ，部署後還是會被 /usr/share/rime-data/default.yaml  寫過去

如果把我的 default.custom.yaml 強制 cp 到 /usr/share/rime-data/default.yaml 那就可以設定好，但是每次 package 更新，果然就會被還原。

我用 Manjaro + KDE (基本上是 Arch Linux），ibus-rime 的 package 用 pacman 灌入，目前安裝的版本是
 - ibus 1.5.23
 - ibus-rime 1.4.0-2

請問有什麼方法嗎？ :pray:

**Comment by lotem** [comment]
`default.custom.yaml` 和 `default.yaml` 的格式不一樣。請參閱文檔的這一部分 https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
