### ISSUE TITLE
Input source disappear in Ubuntu 14.04

### ISSUE THREAD

**Issue by malsony** [rime/ibus-rime#12]
Used quite well for the first time and a second time, but several days later, the input source logo is still there in the status bar, but the "Chinese (rime)" cannot be found, even I logged in as root. I have tried:

```bash
sudo apt-get purge ibus-rime librime-data-wubi -y
```
and then

```bash
sudo apt-get install ibus-rime librime-data-wubi -y
```

but the nothing has changed...

I installed ibus-rime as root, and used as a power user, but now I can't find how to active the input source...

Any idea? Thanks!

**Comment by osfans** [comment]
Is ibus-engine-rime running?
`ps aux|grep rime`
Try this:
`ibus restart`
Any log in `/tmp/rime.ibus.ERROR` or `/tmp/rime.ibus.INFO`?

**Comment by malsony** [comment]
Thanks for your reply!
rime is not running.
and an error message came out after ```ibus restart``` and it said:
```
Can't connect to IBus.
```
Found no log called either ```rime.ibus.ERROR``` or ```rime.ibus.INFO```.

**Comment by malsony** [comment]
I guess it was because of permission settings of the configuration file?

**Comment by osfans** [comment]
First:
`ibus-daemon -drx`
Then:
`ibus restart`

**Comment by malsony** [comment]
Thank you for your reply! I tried by it didn't work. I guess it was because of the permission issue. I rolled back the system and reinstalled Rime, and everything is fine up till now.
