### ISSUE TITLE
当点选 “Show Keyborad layout”时，无法查看键盘布局且会引发崩溃报告

### ISSUE THREAD

**Issue by inoton** [rime/ibus-rime#120]
系统环境：
OS  Fedora 33 64-bit
GNOME Shell 3.38.3
Windowing System Wayland
ibus-rime-1.4.0-6.fc33.x86_64

当点选 “Show Keyborad layout”时，会引发崩溃报告且无法查看键盘布局：
```
Jan 28 23:58:09 audit[34091]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=34091 comm="gkbd-keyboard-d" exe="/usr/bin/gkbd-keyboard-display" sig=11 res=1
Jan 28 23:58:09 kernel: gkbd-keyboard-d[34091]: segfault at 40 ip 00007fd55540480a sp 00007ffed21fdd00 error 4 in libgnomekbdui.so.8.0.0[7fd5553fc000+a000]
Jan 28 23:58:09 systemd-coredump[34099]: Process 34091 (gkbd-keyboard-d) of user 1000 dumped core.
                                         #32 0x0000560650e154a4 main (gkbd-keyboard-display + 0x14a4)
                                         #34 0x0000560650e155ae _start (gkbd-keyboard-display + 0x15ae)
```

将 /usr/share/ibus/component/rime.xml 中的：
<layout>default</layout>  变更为 <layout>us</layout> 后，故障消失。

**Comment by lotem** [comment]
從崩潰報告的信息看，顯示佈局圖的功能是GNOME做的。　
一般情況，ibus-rime應使用默認佈局，以支持美式佈局以外的鍵盤。
除非如注音等輸入法必須使用美式佈局，而與默認佈局不同時，纔有必要限定爲`us`。

**Comment by inoton** [comment]
感谢，大概理解。
曾使用 ibus-table 五笔很长时间，它也有"查看键盘布局"功能，印象中从来没有类似崩溃的段错误提示。
大多数像我这样普通用户，由于不具备判定是谁出问题的能力，而误认为该软件尚未稳定，可能有导致不知情使用者流失情况。
即“没有具体的布局可看”，是否有将其隐藏掉（或其它方案）的可能；毕竟它如此明是在面板上，其义就是引导人们去点击。

**Comment by lotem** [comment]
不瞭解這個功能。
形碼可能需要關心鍵盤佈局。拼音之類的方案用任意拉丁字母佈局都可以。
我覺得你可以向GNOME開發者反饋。據我所知ibus的輸入法引擎除了聲明使用的鍵盤佈局之外，並沒有指令要系統設置顯示鍵盤佈局圖，也沒有針對此功能的代碼實現。

**Comment by inoton** [comment]
了解，谢谢
