### ISSUE TITLE
双屏使用 Telegram desktop 时，输入法候选条会出现在第二块屏幕上

### ISSUE THREAD

**Issue by gokeeper** [rime/ibus-rime#125]
如题，如果 telegram 在屏幕1上时，输入法候选条会出现在第二块屏幕上。如果 telegram 在屏幕2时正常。
Ubuntu 20.04 + wayland

**Comment by lotem** [comment]
​請向 https://github.com/ibus/ibus/issues 反饋。
ibus-rime 自己不實現用戶界面。
