### ISSUE TITLE
请问如何为每个app配置默认英文

### ISSUE THREAD

**Issue by JianJunYuan** [rime/ibus-rime#126]
rt，windows是通过“weasel.custom.yaml”文件配置的，但是ibus中并无该文件

**Comment by lotem** [comment]
沒有這項功能。
ibus沒有給每個應用程序單獨建立輸入法鏈接及維護輸入法狀態，因此只要在輸入方案裏設置初始狀態即可。

**Comment by kamusis** [comment]
请问，是可以理解为在Linux下面就无法实现，切换到比如terminal窗口就默认使用英文，切换到比如typora就默认使用中文这样的效果吗？

**Comment by talenhao** [comment]
大家是怎么解决的？经常使用密码管理器自动输入，中文输入法造成输入一堆乱码，然后再切英文的情况。

**Comment by madjxatw** [comment]
> 沒有這項功能。 ibus沒有給每個應用程序單獨建立輸入法鏈接及維護輸入法狀態，因此只要在輸入方案裏設置初始狀態即可。

作为Linux最主流桌面的御用输入法框架，这种功能都没有实现，哎...
