### ISSUE TITLE
候选词横向排列在 1.50 版本中失效

### ISSUE THREAD

**Issue by inoton** [rime/ibus-rime#131]
# 系统 和 软件包信息如下:
```
~ $ uname -rios
Linux 5.13.1-300.fc34.x86_64 x86_64 GNU/Linux

~ $ rpm -qa | grep ^ibus
ibus-libs-1.5.24-5.fc34.x86_64
ibus-gtk3-1.5.24-5.fc34.x86_64
ibus-setup-1.5.24-5.fc34.noarch
ibus-1.5.24-5.fc34.x86_64
ibus-gtk2-1.5.24-5.fc34.x86_64
ibus-rime-1.5.0-1.fc34.x86_64

librime-1.7.2-1.fc34.x86_64


```
- `~/.config/ibus/rime/ibus_rime.yaml` 将在部署后被自动移除（但在 1.4.X 版本中有效），文件中的内容：
```
style:
  horizontal: true
```
- 同时在 ibus-setup 中已设置为 “候选词横向排列”  但无效。

**Comment by zhmars** [comment]
@inoton  问题解决了吗，如果没有可以试试这个

```yaml
config_version: '1.0'

style:
  horizontal: true
```

**Comment by inoton** [comment]
> @inoton 问题解决了吗，如果没有可以试试这个
> 
> ```yaml
> config_version: '1.0'
> 
> style:
>   horizontal: true
> ```

解决了，谢谢！
后来跟朋友讨论的过程中偶然想到了的方法 ，
`ibus_rime.yaml` 重命名为 ` ibus_rime.custom.yaml  `
内容：  
```
patch:
  style/horizontal: true      # 候选列表横排
```
