### ISSUE TITLE
最新版本Chromium类浏览器(Chrome,Brave,Edge)删除候选框内容会影响正文区域的内容

### ISSUE THREAD

**Issue by aaftio** [rime/ibus-rime#132]
使用的是Ubuntu 20.04.2 LTS操作系统，在这两天的Chrome升级后发现此问题，还不确定是否是ibus-rime的兼容问题，还是rime核心问题，把Brave，Edge升级到最新版本后，也出现了此问题。

1. 操作系统的其它软件，例如Firefox没有出现问题
2. “海峰五笔”在Chrome上不会有这样的问

具体现象如下：
![Peek 2021-07-29 11-23](https://user-images.githubusercontent.com/1856880/127427552-cae27d0b-f72b-4551-81cc-1dd1e22586f6.gif)

**Comment by lotem** [comment]
​參考macOS上對Chrome相同問題的討論：
https://github.com/rime/squirrel/issues/299#issuecomment-506131943
https://github.com/rime/squirrel/issues/435#issuecomment-766084479

**Comment by aaftio** [comment]
> ​參考macOS上對Chrome相同問題的討論：
> [rime/squirrel#299 (comment)](https://github.com/rime/squirrel/issues/299#issuecomment-506131943)
> [rime/squirrel#435 (comment)](https://github.com/rime/squirrel/issues/435#issuecomment-766084479)

谢谢提示，不过后来我发现我安装的是apt仓库里的，版本太低了。当我使用git仓库自己编译安装后，即使没有进行配置更改问题也已经自动解决了。
请问，apt仓库没有更新了么？

**Comment by jimmy09140456** [comment]
我原來是沒有問題的，但更新了Brave後便出現刪除的問題。添加了preedit: true也無法解決問是，是否與Brave更新了有關系？

**Comment by aaftio** [comment]
> 我原來是沒有問題的，但更新了Brave後便出現刪除的問題。添加了preedit: true也無法解決問是，是否與Brave更新了有關系？
> 
> ```
> $ cat default.custom.yaml 
> patch:
>   style/inline_preedit: true
> ```

你看看你当前的rime版本，如果是apt安装的，可能版本太低了，自己编译最新版本，即使不配置问题也会消失。
不过我最近发现了一点新问题，还得花点时间测试，现在新的问题是随机的，不好确认

**Comment by zou2699** [comment]
新版本92.0.4515.131 似乎已经修复了该bug。
`7b793297 Fix backspace event triggered twice problem. `
https://chromium.googlesource.com/chromium/src.git/+log/refs/tags/92.0.4515.131

**Comment by jimmy09140456** [comment]
如果用ibus自帶的輸入法是沒有問題的，所以覺得奇怪，會不會是RIME導致？
我用的是apt裏的舊版，有空我試試看最新版。謝謝

**Comment by aaftio** [comment]
> 新版本92.0.4515.131 似乎已经修复了该bug。
> `7b793297 Fix backspace event triggered twice problem. `
> https://chromium.googlesource.com/chromium/src.git/+log/refs/tags/92.0.4515.131

刚刚升级了，的确没有问题了。
所以我的最终测试结果表明，光是升级rime到最新版本，解决了我在一楼发的第一张图的问题，但是还存在其它问题，比如光标选中了一个字，按一次删除键，会有概率的删除两个字的现象，如下图：
![Peek 2021-08-04 15-08](https://user-images.githubusercontent.com/1856880/128137437-f604718c-0879-4bc7-8935-7f4bb64c0413.gif)

所以，我这边最终升级了chrome到`92.0.4515.131`，rime自己编译最新版本（有可能不升级也行），解决了所有问题。

但是由于Brave和Edge当前最新版本都还没有修复这个问题，所以我上图演示的现象在Brave和Edge上都还能重现。

**Comment by aaftio** [comment]
随着各大基于Chromium的浏览器edge，chrome，brave，vivaldi都升级92.0.4515.131以上，问题都不再重现了，问题关闭了

**Comment by chenhaowen01** [comment]
> 随着各大基于Chromium的浏览器edge，chrome，brave，vivaldi都升级92.0.4515.131以上，问题都不再重现了，问题关闭了

我的edge版本是Microsoft Edge 93.0.961.11 beta，仍然会有这个问题啊

**Comment by zhmars** [comment]
> 我的edge版本是Microsoft Edge 93.0.961.11 beta，仍然会有这个问题啊

前面说的是稳定版，v93 系列需要升级到 `93.0.4577.19` 之后的版本。

**Comment by chenhaowen01** [comment]
> 前面说的是稳定版，v93 系列需要升级到 `93.0.4577.19` 之后的版本。

了解了，多谢！

**Comment by andylinpersonal** [comment]
> (恕刪)
> 请问，apt仓库没有更新了么？

目前只能自己編譯1.5.0 T_T

**Comment by aaftio** [comment]
> > (恕刪)
> > 请问，apt仓库没有更新了么？
> 
> 目前只能自己編譯1.5.0 T_T

不太清楚apt更新的方法，有清楚的可以协助作者更新一下，毕竟可能作者太忙了
