### ISSUE TITLE
ibus-rime stopped working after upgrading yaml-cpp to 0.5.3.

### ISSUE THREAD

**Issue by Wesley-Chan** [rime/ibus-rime#14]
The character selecting box pops up no more.
[This](https://github.com/jbeder/yaml-cpp/commit/ec8aa4fa625257b0db7254460b91b517e2b16a7e) is the commit of yaml-cpp which broke it.

Here's the log.
***
Log file created at: 2016/01/14 11:48:12
Running on machine: localhost
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0114 11:48:12.096580 11681 customizer.cc:129] 'patch' not found in customization file.
W0114 11:48:12.103109 11684 customizer.cc:129] 'patch' not found in customization file.
W0114 11:48:12.154049 11684 deployment_tasks.cc:135] schema list not defined.
***

**Comment by osfans** [comment]
我這邊 librime 重編譯就好了。

**Comment by osfans** [comment]
archlinux 上面的librime已經更新，實測沒有問題。

**Comment by Wesley-Chan** [comment]
Oh, thank you, osfans.
