### ISSUE TITLE
在wayland fractional scaling下，選字框錯位

### ISSUE THREAD

**Issue by iiiian** [rime/ibus-rime#146]
# 如何重現
1. 使用ubuntu 22.04
2. 按照文檔安裝ibus-rime
3. 選擇注音輸入法
4. 於setting->displays->fractional scaling中，使用125% scale
![image](https://user-images.githubusercontent.com/45517361/180596975-d7aa0cfa-a7fb-42a5-b8c0-cb694a577600.png)
5. 在運行於wayland的程式上打字（如libreoffice writer）

**fractional scaling 125%，選字框錯位**
![Screenshot from 2022-07-23 16-07-02](https://user-images.githubusercontent.com/45517361/180597061-13abfee0-c974-4949-bd51-ea1ce171c42f.png)

**fractional scaling 100%，選字框正常**
![Screenshot from 2022-07-23 16-07-26](https://user-images.githubusercontent.com/45517361/180597075-be5bd4c8-e862-48ec-97fb-9129b426dab4.png)

# 版本資訊
ubuntu 22.04
ibus-rime 1.5.0-1: amd64

**Comment by lotem** [comment]
這是ibus的BUG。
