### ISSUE TITLE
Rime appears to ignore the system keyboard layout.

### ISSUE THREAD

**Issue by jonathanknowles** [rime/ibus-rime#15]
Dear Rime Maintainers:

On my system, Rime (version 1.2) appears to ignore the system keyboard layout, and instead acts as if the system keyboard layout is hard-wired to QWERTY.

I installed the "ibus-rime" package on Ubuntu 16.04 LTS:

    $ apt-cache policy ibus-rime
    ibus-rime:
        Installed: 1.2-1build1
        Candidate: 1.2-1build1
        ...

My system keyboard layout is set to US Dvorak:

    # KEYBOARD CONFIGURATION FILE
    # Consult the keyboard(5) manual page.
    XKBMODEL="pc105"
    XKBLAYOUT="us"
    XKBVARIANT="dvorak"
    XKBOPTIONS="compose:ralt"
    BACKSPACE="guess"

Other input methods on my system (such as ibus-libpinyin) correctly observe the system keyboard layout, but if I select Rime, it appears to assume my keyboard is set to QWERTY.

Is there a workaround for this issue?

I'm willing to help with debugging the problem. I've filed a bug for Ubuntu here: https://bugs.launchpad.net/ubuntu/+source/ibus-rime/+bug/1574440

Thanks for your help!
Jonathan

**Comment by jonathanknowles** [comment]
After some debugging, I've found that my system has the "us" layout configured for RIME (by default).

    $ grep layout /usr/share/ibus/component/rime.xml
    <layout>us</layout>

I discovered that the problem goes away if I change this line to the following:

    $ grep layout /usr/share/ibus/component/rime.xml
    <layout>default</layout>

This is the same as your master branch (https://github.com/rime/ibus-rime/blob/master/rime.xml#L19), which also seems to have the correct value of "default".

So I suspect this is a bug in Ubuntu, and possibly Debian.

**Comment by lotem** [comment]
Thanks for reporting, Jonathan.
The change on master was made after ibus-rime 1.2 release.
The issue will be fixed in the next release.

**Comment by jonathanknowles** [comment]
You're welcome! Many thanks for your reply @lotem 

Is there a plan to release a new version of ibus-rime in the near future?

All the best
Jonathan

**Comment by cyqsimon** [comment]
I came across this issue due to a different need.
I type English on Dvorak layout and Chinese on QWERTY layout. So I actually want Rime to **not** use the system's default layout.

In my case,  `<layout>default</layout>` is the default value. I changed it back to `<layout>us</layout>` to force Rime to use QWERTY when switching to Chinese IME.

**Comment by NeedAboutTreeFiddy** [comment]
> In my case, `<layout>default</layout>` is the default value. I changed it back to `<layout>us</layout>` to force Rime to use QWERTY when switching to Chinese IME.

Can you explain like I'm 5 how to you to where you can edit the configuation file?  I want english default and bopomo chinese alternate but I can half my interface KDE in chinese .

**Comment by cyqsimon** [comment]
> Can you explain like I'm 5 how to you to where you can edit the configuation file?

`<sudo> nano /usr/share/ibus/component/rime.xml`

**Comment by leafpool243** [comment]
> I came across this issue due to a different need. I type English on Dvorak layout and Chinese on QWERTY layout. So I actually want Rime to **not** use the system's default layout.
> 
> In my case, `<layout>default</layout>` is the default value. I changed it back to `<layout>us</layout>` to force Rime to use QWERTY when switching to Chinese IME.

@cyqsimon Thank you! It was annoying me that my Bopomofo/Zhuyin layout was getting messed up.
