### ISSUE TITLE
ibus-rime这东西怎么隐藏掉？

### ISSUE THREAD

**Issue by bleedingfight** [rime/ibus-rime#151]
![Screenshot_20221030_114826](https://user-images.githubusercontent.com/11495161/198862015-ce0032f0-1a4a-4308-9e7e-de5db4ad368f.png)
这东西怎么隐藏，输入内容的时候经常在输入框前面，非常烦人。

**Comment by ihola777** [comment]
输入法设置 perference，里面有选项可以关闭
