### ISSUE TITLE
候选词位置和底色不对

### ISSUE THREAD

**Issue by ahxxm** [rime/ibus-rime#16]
archlinux+i3wm，分辨率4k，dpi 175。

xfce4-terminal里候选词在正确位置，Chrome里就飞到窗口外了。。
![image](https://cloud.githubusercontent.com/assets/1286225/19269771/fd36c018-8fee-11e6-82f4-e3c61f5b64d0.png)

![image](https://cloud.githubusercontent.com/assets/1286225/19269786/081da884-8fef-11e6-82c2-882021a8820f.png)

**Comment by ahxxm** [comment]
另外manjaro+i3wm时选词底色会导致上面的字几乎看不见，不知道是不是[自定义皮肤](https://github.com/ahxxm/rime_config/blob/master/squirrel.custom.yaml)导致的。。不过同样配置上面的arch没问题

 
![image](https://cloud.githubusercontent.com/assets/1286225/19270310/deaf8c62-8ff1-11e6-9b5f-551fd7e1416b.png)

**Comment by lotem** [comment]
選字界面是 IBus 控制的。

**Comment by ahxxm** [comment]
thank you, i've append screenshots to [related issue](https://github.com/ibus/ibus/issues/1806) and found my own comment...

**Comment by roachsinai** [comment]
@ahxxm 能否分享一下你在linux上的rime配色？你的rime-repo里面的好象是mac上的。

**Comment by ahxxm** [comment]
@roachsinai 也是那一套，你遇到了啥问题？

**Comment by roachsinai** [comment]
@ahxxm repo只有squirrel／鼠须管那个给配色了。知道了。。。我用的Gnome，你是i3。Gnome里面ibus配色集成到gnomeshell了，感觉你的配色图标pageup/down挺好看，我修改gnomeshell配置的没看到哪里有修改icon的之后大小。

**Comment by roachsinai** [comment]
@ahxxm 非常抱歉，打扰一下，你的rime可以打出这个字么 http://www.zdic.net/z/b2/js/2B6A5.htm

QAQ

**Comment by ahxxm** [comment]
@roachsinai xia可以打出来，但是我字体显示不了。。要不来我repo开issue？

**Comment by roachsinai** [comment]
@ahxxm 这个字繁体可以，简体不可以。。搞不清楚，应该不是rime配置的问题。如果是配置问题就果断issue了。
