### ISSUE TITLE
ibus-rime can't deploy

### ISSUE THREAD

**Issue by Pygmalion6636** [rime/ibus-rime#17]
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1012 13:18:42.675222 11035 config.cc:699] Error parsing YAML: yaml-cpp: error at line 25, column 6: illegal map value
E1012 13:18:42.675407 11035 customizer.cc:117] Error loading customization file.
E1012 13:19:21.041139 11296 config.cc:699] Error parsing YAML: yaml-cpp: error at line 25, column 6: illegal map value
E1012 13:19:21.041178 11296 customizer.cc:117] Error loading customization file.
E1012 13:19:21.298444 11296 deployment_tasks.cc:241] source file 'stroke.dict.yaml' does not exist.
E1012 13:19:21.298501 11296 dict_compiler.cc:87] neither stroke.dict.yaml nor stroke.table.bin exists.
E1012 13:19:21.298529 11296 deployment_tasks.cc:300] dictionary 'stroke' failed to compile.

**Comment by lotem** [comment]
某個 `*.custom.yaml` 配置文件語法錯。具體位置已經給出來了，查看 INFO log 找到出錯的文件。

**Comment by lotem** [comment]
Closed as it doesn't seem to be an issue with ibus-rime itself.
