### ISSUE TITLE
如何读取LevelDB table data文件？

### ISSUE THREAD

**Issue by hwypengsir** [rime/ibus-rime#178]
luna_pinyin.userdb文件夹内有000005.ldb文件。

    file /home/debian/.config/ibus/rime/luna_pinyin.userdb/000005.ldb
    /home/debian/.config/ibus/rime/luna_pinyin.userdb/000005.ldb: LevelDB table data

这个文件可以用`xxd` and `vim` 打开，它不是空的。

    import plyvel
    dbfile = "/home/debian/.config/ibus/rime/luna_pinyin.userdb/000005.ldb"
    db = plyvel.DB(dbfile)

报错信息：

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
      File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
    plyvel._plyvel.IOError: b'IO error: /home/debian/.config/ibus/rime/luna_pinyin.userdb/000005.ldb/LOCK: Not a directory'

请问：为何无法用pythond的plyvel打开？有无bash的命令可以打开？

  [1]: https://i.stack.imgur.com/iUymm.png

**Comment by fxliang** [comment]
![image](https://github.com/rime/ibus-rime/assets/4023160/b58ac103-fe7a-4fc6-8f82-aab7ad2be997)
https://plyvel.readthedocs.io/en/latest/user.html#getting-started

> plyvel._plyvel.IOError: b'IO error: /home/debian/.config/ibus/rime/luna_pinyin.userdb/000005.ldb/LOCK: Not a directory'

运行报错信息已经很清晰了


明显你并不熟悉plyvel，看文档可解决

```python
import plyvel
dbfile = "/home/debian/.config/ibus/rime/luna_pinyin.userdb/"
db = plyvel.DB(dbfile)
```
