### ISSUE TITLE
Ubuntu 16.10依赖libopencc 1.0.4，导致简体无法转换

### ISSUE THREAD

**Issue by zhaobaiyu** [rime/ibus-rime#18]
simplifier.cc:126] Error initializing opencc: t2s.json not found or not accessible.

选择简体输出的是繁体，无法完成转换，不知道怎么解决……

添加 /usr/share/opencc/ 里的文件还是不管用。

**Comment by GavinLi369** [comment]
@zhaobaiyu 
請問您最後是怎麼解決的？

**Comment by zhaobaiyu** [comment]
@GavinLi369 没有解决，没折腾，感觉这个repository没人管理，所有关了issue，暂时用其他输入法。依赖问题应该不难解决， @lotem 在其他issue下面也说了，等更新吧。

**Comment by GavinLi369** [comment]
好吧，謝謝

**Comment by amitbha** [comment]
@GavinLi369 
我解决了，是上游打包的opencc有问题，少了数据文件。
opencc有github，把data文件夹里的*.json，*.txt都拷到/usr/share/opencc目录下，比如t2s.json，TWVariants.txt等
然后使用opencc_dict程序把这些txt转为ocd格式，完毕。

**Comment by GavinLi369** [comment]
@amitbha 
厉害，按你的方法弄好了。

**Comment by KagamiChan** [comment]
搜索来到这里的
debian 的 opencc git 里面 9 月份已经修复了这个问题，然后多出了一个 libopencc2-data 的包，我自己打了一份包……
[libopencc2-data_1.0.4-2_all.deb.zip](https://github.com/rime/ibus-rime/files/566869/libopencc2-data_1.0.4-2_all.deb.zip)

**Comment by Frederick888** [comment]
@amitbha 多谢，已经解决，用的 @KagamiChan 发上来的包，解包之后直接把文件复制过去的

**Comment by hosiet** [comment]
下游 bug 跟踪地址：
http://bugs.debian.org/836395

**Comment by Sciroccogti** [comment]
目前似乎已经不需要下载 @KagamiChan 的包了，Ubuntu 18.04 已经提供 1.0.4-5 的 libopencc2-data
