### ISSUE TITLE
请求支持 ubuntu 24.04

### ISSUE THREAD

**Issue by Pathsis** [rime/ibus-rime#180]
目前运行 `sudo apt install ibus-rime`，无法安装了。

**Comment by Pathsis** [comment]
已支持，谢谢！可能是软件源更新的有点晚。

**Comment by sunny-zhang-98** [comment]
@Pathsis 24 上好像有些应用的输入框上屏有问题，你遇到过吗

**Comment by Pathsis** [comment]
@sunny-zhang-98 目前ibus-rime在任何gnome应用上输入，都会多输出拼音字母。不知道您遇到的问题是不是这样？

[录屏 2024-05-26 14-24-21.webm](https://github.com/rime/ibus-rime/assets/72077265/8ea10c0e-7ebd-45f7-8b84-078deb2c0bdd)

**Comment by sunny-zhang-98** [comment]
@Pathsis 是这样的而且我原本设置的横排显示候选词也不生效了
