### ISSUE TITLE
wps打字看不到字母只有候选词

### ISSUE THREAD

**Issue by theLSA** [rime/ibus-rime#187]
操作系统：debian

ibus-rime:
[https://github.com/hchunhui/ibus-rime.AppImage](https://github.com/hchunhui/ibus-rime.AppImage)

配置：
https://github.com/iDvel/rime-ice/

比如打fac，没有出现fac这三个字母，只有候选词。其他应用如sublime text和浏览器都正常出现字母。

![ibus-rime-no-words-00](https://github.com/user-attachments/assets/560c0f2b-bf49-4d55-9aa9-fa7a7b0231bc)

尝试的方案：
在.zshrc加入

`# iBus always on 
export INPUT_METHOD="ibus"
export XMODIFIERS="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"
export QT4_IM_MODULE="ibus"`

无效。

**Comment by illusionist-moon** [comment]
目前我的解决方法是打patch，加上`style/inline_preedit: false`
但是这种解决方法并不优雅，主要体现在：在一些应用中（例如fedora41 gnome自带的终端），有时会出现输入法的候选词框显示层级较低的情况，需要鼠标点击本就已经聚焦的输入区域以再次聚焦，来提升候选词框显示层级。

**Comment by lotem** [comment]
其他應用好使, 那大概是 WPS 的錯吧?
或者查查 ibus 那裏有沒有記錄. ibus-rime 不直接跟應用對接, 中間隔着 ibus.
