### ISSUE TITLE
Can't input two "#" symbol

### ISSUE THREAD

**Issue by stskyblade** [rime/ibus-rime#189]
My environment：
OS: Manjaro Linux
DE: KDE Plasma 6.0.5
ibus-rime

When edit Markdown file, it's common to input two or three "#" symbol. But when I type the second "#", it just move to the next candidate word, rather than input "#" symbol.

When I type one "#":
![image](https://github.com/user-attachments/assets/7e82e9fe-9acc-490b-a5a5-c76748de43eb)

When I type the second "#":
![image](https://github.com/user-attachments/assets/d8553c57-2d1e-45aa-b093-a43cabb8062c)

What I expected:
Just input two "#" symbol.

**Comment by lotem** [comment]
每個 # 之後按一下空格。或者切換這個選項：
<img width="306" alt="Screenshot 2024-08-31 at 14 06 30" src="https://github.com/user-attachments/assets/8d6baac5-da74-4d3e-b09c-108c071f7658">

**Comment by lotem** [comment]
不是 BUG，而是配置實現的符號候選功能。因此關閉。
