### ISSUE TITLE
这个候选字词框离得很远，怎么修改这个位置？

### ISSUE THREAD

**Issue by jackoelv** [rime/ibus-rime#193]
如果是在屏幕下方，这个候选字词框就看不见了。
4K屏幕，wayland下面，就会有这个问题，如附件的截图。

假设我在这里
如果我在这里就看不见了？
![截图 2024-12-18 20-35-10](https://github.com/user-attachments/assets/4fbaf1d7-c2b6-476b-97ab-2e3922c252b6)
![截图 2024-12-18 20-37-25](https://github.com/user-attachments/assets/169062bb-92fc-40e8-a3b8-6d2ee5efedd0)
![截图 2024-12-18 20-37-01](https://github.com/user-attachments/assets/a7b98d89-d0ca-4c64-a752-32f7285371f2)
![截图 2024-12-18 20-36-47](https://github.com/user-attachments/assets/692c56b2-c6dc-42cd-9a4e-cdd25d76daca)

ru guo wo zai zhe li jiu kan bu jian le

**Comment by lotem** [comment]
可能是 ibus 的錯？
輸入法界面是 ibus  的，rime 無法控制啊。
