### ISSUE TITLE
Icons display incorrectly

### ISSUE THREAD

**Issue by Rapiz1** [rime/ibus-rime#23]
OS: Archlinux 64-bit
DE: Gnome 3.22.2 on Wayland

I just installed arch and installed ibus-rime, however, got a white square instead of the icon on tray. Everything seems to be fine expect the icon.

have failed to upload a pic because of the slow network.

have checked /usr/share/ibus-rime/icons and everything seemed to be fine.

**Comment by lotem** [comment]
Depending on ibus' UI component, either `icons/rime.png` or a Unicode character specified in the XML is displayed as the tray icon:
https://github.com/rime/ibus-rime/blob/master/rime.xml#L23

If you the Chinese character [㞢] doesn't render correctly, you may need to install a Chinese font.
You can also edit the XML to show a different symbol.

**Comment by Rapiz1** [comment]
Actually I have installed wqy-mircohei before.  However it doesn't seem to contain a character [㞢] in it. So I installed wqy-zenhei. Then the icon displays correctly.

Thanks.
