### ISSUE TITLE
中英文标点转换提示词

### ISSUE THREAD

**Issue by LYF610400210** [rime/ibus-rime#24]
![。，→.,](https://cloud.githubusercontent.com/assets/6359921/21579777/48b65e74-cf76-11e6-8243-7dfb1dd3e705.png)
第一次使用的时候根本没看到。建议把提示词改成 __“中文标点→西文标点”__ 之类的吧。

**Comment by osfans** [comment]
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin.schema.yaml#L29

可以修改此schema 也可以去rime/home那边学习讨论。

**Comment by lotem** [comment]
不理解爲什麼選項 5. 是灰字？其他（未選中）選項都是更亮的白色。沒看到是不是這個原因。

**Comment by LYF610400210** [comment]
@lotem 截图的时候鼠标放上去了。

`[ 。，, ．， ]`比较不明显，刚开始用的时候以为是翻页选项。
