### ISSUE TITLE
ibus-setup fails with local python3, how to lanuch rime?

### ISSUE THREAD

**Issue by Michael728** [rime/ibus-rime#27]
I install rime : 
- `sudo apt-get install ibus-rime`, 
- `F4` to choose the rime
Firstly, ibus-setp can works, but when I install Anaconda, and python is set to python3, error happens: https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1611523, I can not launch rime and ibus-setup does not work

**Comment by lotem** [comment]
That's not an issue with Rime since ibus-rime doesn't use python. You should first make IBus work.
