### ISSUE TITLE
ibus 下 rime 候选词乱码

### ISSUE THREAD

**Issue by mritd** [rime/ibus-rime#28]
找了很多文章,大部分给出的解决方案是使用 HanaMinA 字体,我尝试切换 IBUS 字体到这个以后仍然乱码;遇到比较坑的是乱码问题会造成 IDEA bug, 情况是只要出现了乱码 IDEA 中就会出现两个框框;这两个框框可以删除,但是只要接下来输入任意中文,框框就会重复出现,而且会导致后面代码被莫名其妙的删掉;所以没办法了只能来这里求助

![image](https://cloud.githubusercontent.com/assets/13043245/26518105/5cbaac44-42db-11e7-90cd-28e5df57a1b1.png)
![image](https://cloud.githubusercontent.com/assets/13043245/26518106/677f248e-42db-11e7-8f14-2856dc21e450.png)

**Comment by lotem** [comment]
輸入窗口所顯示並非亂碼，而是字體缺字，俗稱豆腐塊。

http://www.zdic.net/z/a5/js/28216.htm
這個字屬於 Unicode 擴充-B 字集。
收錄於「花園明朝 B」。而花園明朝 A （HanaMinA.ttf）未收錄。
http://fonts.jp/hanazono/

> 花園明朝B（HanaMinB.ttf）
> 52,943字
>
> CJK統合漢字（Ext.B、Ext.C、Ext.D、Ext.E）

至於 IDEA 的 bug，與輸入法能否正確顯示沒有直接關係。有可能只是字體支持的問題，但就你的描述看也不能排除該軟件 Unicode 處理出了問題。

**Comment by mritd** [comment]
感谢,使用 花園明朝B 候选栏可以显示了,但是貌似是 IDEA 的 bug,这个特殊字符还是无法在 IDEA 中存在, 同时请教以下 ibus 下能否将这些扩充子集禁用掉?

**Comment by lotem** [comment]
使用 `charset_filter`
參考 https://github.com/rime/librime/issues/59
