### ISSUE TITLE
我编制了一个“单手笔顺输入法”的码表，希望RIME输入法能加入这个功能，为Linux版和windows版电脑用户提供一个新的选择

### ISSUE THREAD

**Issue by YQ-YSY** [rime/ibus-rime#34]
RIME输入法的开发者：
你们好！
我编制了一个“单手笔顺输入法”的码表，希望RIME输入法能加入这个功能，为Linux版和windows版电脑用户提供一个新的选择

开源项目网址： https://github.com/YQ-YSY/stroke-seq_MB
发布在Ubuntu论坛的帖子介绍：
http://forum.ubuntu.org.cn/viewtopic.php?f=35&t=484603

**Comment by Prcuvu** [comment]
请参考[rime/rime-stroke](https://github.com/rime/rime-stroke)中码表的格式，把词条贡献到这个仓库，谢谢。

至于按键的不同，可以另写一个方案文件，重新设置按键映射。

**Comment by lotem** [comment]
I think your description is not an issue but an information.
ibus-rime itself is a software platform to support various input methods. Input methods that run on ibus-rime are not part of this project but maintained separately by multiple authors.
Please consider creating an [input schema](https://github.com/rime/home/wiki/RimeWithSchemata) for Rime in your project's existing code repository or create a new repository.
