### ISSUE TITLE
能否关闭 ibus-rime 初始化时弹出的通知？

### ISSUE THREAD

**Issue by yueduz** [rime/ibus-rime#37]
![2017-12-03 09-39-42](https://user-images.githubusercontent.com/1448159/33521517-826e4aea-d80e-11e7-8c28-6c52a779b032.png)

**Comment by Prcuvu** [comment]
外部没有关闭的方法。这是设计思路的问题，我认为不能。

**Comment by yueduz** [comment]
点部署弹出就行了，可现在是每次开机都弹出。以前不会这样

**Comment by lotem** [comment]
It is deploying data on every startup because of a bug.
https://github.com/rime/librime/issues/164

**Comment by gapplef** [comment]
@lotem Is this bug fixed?
I'm using ibus-rime v1.4.0 on Ubuntu 20.04.
I still get these annoying notifications at every system startup.
![rime](https://user-images.githubusercontent.com/5604665/87905056-4af7a100-ca92-11ea-906b-d589984cd9b6.png)

How can I get rid of it?

**Comment by lotem** [comment]
@gapplef yes it's fixed. i've seen it a few times but i don't have these notifications on my linux desktop now.
try find errors in the [log](https://github.com/rime/home/wiki/RimeWithSchemata#%E9%97%9C%E6%96%BC%E8%AA%BF%E8%A9%A6). i can tell you that if any error exists in your configuration and data is not fully updated, it'll try again on next start.

**Comment by gapplef** [comment]
@lotem In `/tmp/ibus.WARNNING` I found the following message:
> nonexistent config file '/home/julian/.config/ibus/rime/ibus_rime.yaml'.

Is this the reason for the notifications on startup? How to fix it?

**Comment by gapplef** [comment]
@lotem Thanks for you help!
Seems there is some thing wrong with my config.
After delete `~/.config/ibus/rime` and regenerate the config, problem fixed.
