### ISSUE TITLE
最新版本的Rime，在IDEA 2017.2版本中书写汉字的时候，光标位置和输入法显示位置不一样，如下图

### ISSUE THREAD

**Issue by wangchangsong** [rime/ibus-rime#38]
最新版本的Rime，在IDEA 2017.2版本中书写汉字的时候，光标位置和输入法显示位置不一样，如下图：
![image](https://user-images.githubusercontent.com/18513995/33647589-d08aba9a-da90-11e7-9e38-7b6b967dbf00.png)
还有在submile中也是这个问题，不知道有没有解决的办法

**Comment by osfans** [comment]
應該是ibus的問題。建議去ibus那邊反應。

**Comment by wangchangsong** [comment]
我的系统是windows系统

**Comment by Prcuvu** [comment]
> 應該是ibus的問題。建議去ibus那邊反應。

这是小狼毫0.9.30版本。
