### ISSUE TITLE
Can not switch the order of 借 and 藉

### ISSUE THREAD

**Issue by mamsds** [rime/ibus-rime#40]
By rights, if I input a character more than any others with the same pinyin, it should be in the first place in a list of candidates. However,strangely enough, no matter how many times I input the character 借, it is always in the second place, after 藉, which I seldom use. Is this a bug? Are there any workarounds?

(Two years ago there was a similar feedback on Baidu Tieba: http://dq.tieba.com/p/4190358375)

Thanks,

照理来说，我打一个字的次数比其他同拼音的字的次数更多，他就会被排在候选字列表的第一位。然而，奇怪的是，不论我输入多少次“借”，他始终只能排在第二位，在我不常用的“藉”字的后面。这个是一个bug吗？有没有什么方法固定“借”字到首位？

（两年前在百度贴吧有一个类似的案例：http://dq.tieba.com/p/4190358375）

谢谢！

**Comment by Prcuvu** [comment]
`simplifier` 使用 OpenCC 进行字形转换。如果出现了一对多的转换：
```
藉	藉 借
```
并在开启 `simplifier` 的情况下输入一对多转换中转换后的字形，将会把该组所有的转换结果整体提高排序，内部顺序不调整排序。不知道是不是有意设计的。

**Comment by mamsds** [comment]
那请问是不是如果要输入简体字就必须用到simplifier？也就是我无法通过避免使用simplifier来回避这个问题？
谢谢！

**Comment by lotem** [comment]
要避免這個問題，（不需要簡繁轉換的情況下 ）最簡單的辦法是不用「朙月拼音」，換成簡體的詞典。

類似還有構詞後保存新詞的問題。

而我需要做兩件事：
從數據的質量看，應提高「借」的權重；
根本解法是合理更新權重，設法加到「借」字頭上，或者讓「借」比「藉」權重增加得多些。但是現實情況卻十分困難：
簡體模式下的候選字「借」，可能是「藉」簡化來的「借」與傳承字「借」合併的結果，也有可能只是前者——因爲候選詞列表是惰式加载的，如果傳承字「借」排在當前頁以外，則尚未發生合併。
無論是哪種情況，如果「藉」的初始權重高於「借」，則按照平分策略增加權重永遠無法調整兩字的相對次序。

**Comment by lotem** [comment]
第二個辦法是修改 OpenCC 詞典，取消這條轉換規則。
缺點是「借」無法分到「藉」的一部分字頻，得在 `essay` 裏面調整好。
