### ISSUE TITLE
倉頡5的字典只有前半段是有效的？

### ISSUE THREAD

**Issue by SuWeiBo** [rime/ibus-rime#41]
作業系統是 `LinuxMint 18.3`，我去 `/usr/share/rime-data/cangjie5.dict.yaml` 找了字典來看，能夠生效的碼表只到 `yyyyo` （第24064行）
我需要再設定什麼才能使用之後的碼表嗎？或是我該嘗試著自行編譯？
順便問下，自訂碼表可以輸入 `Tab` 這樣的特殊字元嗎？

**Comment by lotem** [comment]
如果懷疑字典文件不完整，可以刪除以下兩處的 `.bin` 文件（保留 `.yaml` 文件），然後按「部署/Deploy」按鈕或菜單項重新在用戶目錄重新生成字典。
`$HOME/.config/ibus/rime/cangjie5.*.bin`
`/usr/share/rime-data/cangjie5.*.bin`

`Tab` 用作字段分隔符，無法識別爲字典中的文字。

**Comment by lotem** [comment]
很可能不是字典的問題。
後面那些字屬於擴展字符集。
請調出方案選單，選擇「常用→增廣」菜單項。
