### ISSUE TITLE
ibus-rime在ubuntu18.04环境下按Shift键切换中英文状态时，输入法图标无变化

### ISSUE THREAD

**Issue by grassvalley** [rime/ibus-rime#50]
ibus-rime在ubuntu18.04环境下按Shift键切换中英文状态时，输入法图标无变化。
按照一般原则，中文输入法按下Shift键可以快速切换中英文状态，这个时候系统指示区的输入法图标会变化图标，以提示用户中英文状态发生了变化。比如ibus-libpinyin即是如此。

软件环境：ubuntu 18.04 64位版，原生桌面环境

**Comment by cmmei** [comment]
我更新到 ubuntu 18.04 之后，ibus-rime 无法在 Atom 输入中文，其他程序里正常。

**Comment by Sciroccogti** [comment]
或者可以像小狼毫那样 给一个弹窗？

![image](https://user-images.githubusercontent.com/32357397/79422161-efc79580-7fee-11ea-8fb9-5d0fb4b54559.png)![image](https://user-images.githubusercontent.com/32357397/79422185-fd7d1b00-7fee-11ea-9729-f7b581d97918.png)

**Comment by lotem** [comment]
最新gnome-shell集成的輸入法圖標已經實現了這個功能，Rime輸入法的狀態顯示爲中文輸入方案名的首字或「A」。
目前ibus-rime完全採用IBus提供的界面。

**Comment by shukebeta** [comment]
很高识看到这个问题有了一个答案，但我自己这个ubuntu18.04实例里面，图标仍然没有变化。我猜测是我没有安装必要的图标，但我不知道该如何安装， @lotem 可否稍详细一点讲一讲如何安装这些图标？

**Comment by shukebeta** [comment]
我解决了这个问题！解决方法是从源码安装 ibus-rime。从github下载了源码，并按照文档说明事先安装好所有的依赖。然而当我执行 ./install.sh 仍然可耻的失败了。幸运的是，源码里还有一个 install-static.sh 脚本，这个脚本可以编译成功并安装。现在我的五笔拼音也能够识别中英方式了（英文状态显示A，中文状态显示“五”），太开心了！

我是 ubuntu 18.04 (pop!os) Gnome 3 桌面，五笔拼音输入法

为方便同样用 ubuntu 18.04 的同学，我把编译前的准备工作和编译步骤列在下面：

sudo apt install cmake libboost-all-dev libibus-1.0-dev libnotify-dev libgoogle-glog-dev libkyotocabinet-dev libleveldb-dev libmarisa-dev libopencc-dev libyaml-cpp-dev

然后 clone project and submodules:

git clone --recursive https://github.com/rime/ibus-rime.git
cd ibus-rime
# do this as normal user
./install-static.sh

安装成功之后，重启 ibus

ibus-damon -dxr 

Enjoy your favorite input method!

**Comment by Sciroccogti** [comment]
@shukebeta 管用！感谢！不過有一個別字：`ibus-daemon -dxr`

另外似乎 `ibus restart` 亦可重啓 ibus

PS：我在 Ubuntu 18.04 遇到了無法輸出簡體的問題，似乎與現有的各 issue 不同。不知你是否也遇到了
