### ISSUE TITLE
/tmp/rime.ibus.ERROR删除后怎么恢复

### ISSUE THREAD

**Issue by fvstar** [rime/ibus-rime#51]
不小心删除了/tmp目录下的rime.ibus.ERROR文件，删除后重新创建此文件发现与rime.ibus.WARNNING以及rime.ibus.INFO文件不同，果然，重新部署后自己创建的rime.ibus.ERROR文件消失。现在每次重新部署ibus-rime显示Rime has encountered an error ，Please see /tmp/rime.ibus.ERROR...可是我没有。。。

**Comment by ASC8384** [comment]
請問您解決這個問題了嗎？

**Comment by YaoLiMuMu** [comment]
i have the same proble, Rime has encountered an error, but there is no such file as /tmp/rime.ibus.ERROR
