### ISSUE TITLE
请问ibus-rime如何设置输入框横排显示

### ISSUE THREAD

**Issue by catfishjones** [rime/ibus-rime#52]
您好，请问ibus-rime1.3.0在最新的gnome3.30环境中如何设置输入框为横排？1.3.0版本中所有的老方法都不管用了，包括改ibus-setup设置页面，终端执行gsettings set org.freedesktop.ibus.panel lookup-table-orientation 0。ibus-setup的方法在kde桌面环境中是有效的。您是否可以考虑在下一个版本中添加一个切换横排竖排显示的开关？gnome环境中的ibus全局设定已经完全失效了，ibus智能拼音的横竖排显示设定也只能在输入法自己的设置页面中更改。测试环境是fedora 29。原来ibus-rime1.2.0的时候一切正常，更新之后就不好使了。

**Comment by zhmars** [comment]
这个问题好像一直没有修复，参考 https://github.com/rime/ibus-rime/issues/42

临时办法是创建 `~/.config/ibus/rime/build/ibus_rime.yaml`，添加以下内容

```yaml
style:
  horizontal: true
```
Gnome 3.30.2 测试通过

**Comment by lotem** [comment]
Duplicate of #42

**Comment by starriv** [comment]
> 这个问题好像一直没有修复，参考 #42
> 
> 临时办法是创建 `~/.config/ibus/rime/build/ibus_rime.yaml`，添加以下内容
> 
> ```yaml
> style:
>   horizontal: true
> ```
> 
> Gnome 3.30.2 测试通过

+1

**Comment by YaoLiMuMu** [comment]
在ubuntu 18 环境下失效，ibus-rime无法横向显示

**Comment by BoyanXu** [comment]
06/27/2019
Arch Linux 环境下的可行办法:

1. 创建空白文件:
`~/.config/ibus/rime/build/ibus_rime.yaml`

2. 向 ibus_rime.yaml 写入并保存以下内容:
```yaml
style:
   horizontal: true
```
3. 重新部署 ibus-rime


参考: https://forums.fedoraforum.org/showthread.php?320042-How-to-set-ibus-rime-to-horizontal-in-fedora-29

**Comment by SunicYosen** [comment]
> 境下失效，ibus-rime无法横向显示

测试在Ubuntu18.04.3, Gnome3.28下：

> 1. 创建空白文件:
>  \~/.config/ibus/rime/ibus_rime.yaml
>  (\~/.config/ibus/rime/build/ibus_rime.yaml)应该也可以
>
> 2. 向 ibus_rime.yaml 写入并保存以下内容:
> 
> ```yaml
> style:
>    horizontal: true
> ```

有效！谢谢！

**Comment by who3m1** [comment]
> **06/27/2019**
> 
> **Arch Linux**, **Gnome 3.32**, **Wayland** 环境下的可行办法:
> 
> 1. 创建空白文件:
>    `~/.config/ibus/rime/build/ibus_rime.yaml`
> 2. 向 ibus_rime.yaml 写入并保存以下内容:
> 
> ```yaml
> style:
>    horizontal: true
> ```
> 
> 1. 重新部署 ibus-rime
> 
> 参考: https://forums.fedoraforum.org/showthread.php?320042-How-to-set-ibus-rime-to-horizontal-in-fedora-29

Ubuntu 20.04，无效...

**Comment by phyzhenli** [comment]
> 这个问题好像一直没有修复，参考 #42
> 
> 临时办法是创建 `~/.config/ibus/rime/build/ibus_rime.yaml`，添加以下内容
> 
> ```yaml
> style:
>   horizontal: true
> ```
> 
> Gnome 3.30.2 测试通过

ubuntu 20.04.1 因ibus选项无法打开，采用此方法测试通过

**Comment by LZDQ** [comment]
谢谢各位大佬

**Comment by MIracleyin** [comment]
> **06/27/2019**
> 
> **Arch Linux**, **Gnome 3.32**, **Wayland** 环境下的可行办法:
> 
> 1. 创建空白文件:
>    `~/.config/ibus/rime/build/ibus_rime.yaml`
> 2. 向 ibus_rime.yaml 写入并保存以下内容:
> 
> ```yaml
> style:
>    horizontal: true
> ```
> 
> 3. 重新部署 ibus-rime
> 
> 参考: https://forums.fedoraforum.org/showthread.php?320042-How-to-set-ibus-rime-to-horizontal-in-fedora-29

安装 https://github.com/rime/plum 后，可以找到这个配置文件，修改 horizontal: true 即可
archlinux gnome 41 可用

**Comment by uaiqop** [comment]
> 这个问题好像一直没有修复，参考 #42
> 
> 临时办法是创建 `~/.config/ibus/rime/build/ibus_rime.yaml`，添加以下内容
> 
> ```yaml
> style:
>   horizontal: true
> ```
> 
> Gnome 3.30.2 测试通过

manjaro Gnome 45 可用，谢谢大佬

**Comment by Knight912** [comment]
> > **06/27/2019**
> > **Arch Linux**, **Gnome 3.32**, **Wayland** 环境下的可行办法:
> > 
> > 1. 创建空白文件:
> >    `~/.config/ibus/rime/build/ibus_rime.yaml`
> > 2. 向 ibus_rime.yaml 写入并保存以下内容:
> > 
> > ```yaml
> > style:
> >    horizontal: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. 重新部署 ibus-rime
> > 
> > 参考: https://forums.fedoraforum.org/showthread.php?320042-How-to-set-ibus-rime-to-horizontal-in-fedora-29
> 
> 安装 https://github.com/rime/plum 后，可以找到这个配置文件，修改 horizontal: true 即可 archlinux gnome 41 可用

Ubuntu22.04 gnome42可用，感谢

**Comment by Knight912** [comment]
> **06/27/2019**
> 
> **Arch Linux**, **Gnome 3.32**, **Wayland** 环境下的可行办法:
> 
> 1. 创建空白文件:
>    `~/.config/ibus/rime/build/ibus_rime.yaml`
> 2. 向 ibus_rime.yaml 写入并保存以下内容:
> 
> ```yaml
> style:
>    horizontal: true
> ```
> 
> 3. 重新部署 ibus-rime
> 
> 参考: https://forums.fedoraforum.org/showthread.php?320042-How-to-set-ibus-rime-to-horizontal-in-fedora-29

Ubuntu22.04 gnome42可用，感谢

**Comment by Thundercup** [comment]
> 这个问题好像一直没有修复，参考 [#42](https://github.com/rime/ibus-rime/issues/42)
> 
> 临时办法是创建 `~/.config/ibus/rime/build/ibus_rime.yaml`，添加以下内容
> 
> style:
>   horizontal: true
> Gnome 3.30.2 测试通过

ubuntu 25.10 依旧有效，该文件已经存在，直接将false改成true即可

**Comment by lotem** [comment]
```yaml
# ~/.config/ibus/rime/ibus_rime.custom.yaml
patch:
  style/horizontal: true
```

**Comment by Marerc** [comment]
> > 这个问题好像一直没有修复，参考 [#42](https://github.com/rime/ibus-rime/issues/42)
> > 临时办法是创建 `~/.config/ibus/rime/build/ibus_rime.yaml`，添加以下内容
> > style:
> > horizontal: true
> > Gnome 3.30.2 测试通过
> 
> ubuntu 25.10 依旧有效，该文件已经存在，直接将false改成true即可

有用的，rime-ice 也可用

**Comment by thouen** [comment]
> 这个问题好像一直没有修复，参考 [#42](https://github.com/rime/ibus-rime/issues/42)
> 
> 临时办法是创建 `~/.config/ibus/rime/build/ibus_rime.yaml`，添加以下内容
> 
> style:
>   horizontal: true
> 
> Gnome 3.30.2 测试通过

Debian 13 有效

**Comment by VirgilMing** [comment]
fcitx5（@ kde-plasma）: 
（至少安装fcitx5-configtool，可能还要-qt库？）
系统设置 - 输入法 - 经典用户界面 - 垂直候选列表
这个选项控制这个行为

另，字体大小也由fcitx5控制
