### ISSUE TITLE
Where to set color scheme on KDE?

### ISSUE THREAD

**Issue by roachsinai** [rime/ibus-rime#54]
I found people use mac setting in `squirrel.custom.yaml`.

**Comment by lotem** [comment]
`squirrel.custom.yaml` only works for https://rime.im/download/#mac

**Comment by roachsinai** [comment]
So, how about ibus-rime and fcitx-rime on KDE? I found ibus-rime color is setting in gnome-shell.css on Linux Gnome.

**Comment by lotem** [comment]
Rime doesn't implement the user interface on Linux.
It's part of ibus / fcitx.
