### ISSUE TITLE
Input Method Delay

### ISSUE THREAD

**Issue by jared73** [rime/ibus-rime#56]
I use fedora.When two screens are found, the HDMI screen input method delays the card from failing to see the options, while the VGA screen is normal.
Please pay attention. Thank you.

**Comment by nameoverflow** [comment]
Isn't it a ibus issue?

**Comment by jared73** [comment]
but I use fcitx. Do you mean this is an input method platform problem?

**Comment by nameoverflow** [comment]
> Do you mean this is an input method platform problem?

Yea.
And this is the ibus client repo.

**Comment by jared73** [comment]
ok，thank u
