### ISSUE TITLE
编译安装librime后，安装这个报错

### ISSUE THREAD

**Issue by YLXDXX** [rime/ibus-rime#57]
./install.sh
fatal: 不是一个 git 仓库（或者直至挂载点 / 的任何父目录）
停止在文件系统边界（未设置 GIT_DISCOVERY_ACROSS_FILESYSTEM）。
./install.sh: 第 5 行:cd: librime: 没有那个文件或目录
mkdir -p build
(cd build; cmake -DCMAKE_BUILD_TYPE=Release .. && make)
CMake Error at /usr/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find RimeData (missing: RIME_DATA_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindRimeData.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:27 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/shui/Desktop/ibus-rime-master/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:15：ibus-engine-rime] 错误 1

**Comment by lotem** [comment]
ibus-rime 的安裝步驟：
https://github.com/rime/home/wiki/RimeWithIBus#build-and-install-ibus-rime

如果不按文檔上的步驟，單獨編譯安裝 ibus-rime，只須執行
```sh
make && make install
```
