### ISSUE TITLE
Checking for module 'ibus-1.0' --   No package 'ibus-1.0' found

### ISSUE THREAD

**Issue by xukai2025** [rime/ibus-rime#63]
Compile this error, forgive me for being a newbie, please advise~

`-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 

-- Checking for module 'ibus-1.0'

--   No package 'ibus-1.0' found

CMake Error at /usr/local/share/cmake-3.12/Modules/FindPkgConfig.cmake:436 (message):

  A required package was not found
`

**Comment by xukai2025** [comment]
已解决，
yum provedios  "ibus-1.0"
yum install "ibus-1.0"

**Comment by bbadd** [comment]
sudo apt install libibus-1.0-dev
