### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by xukai2025** [rime/ibus-rime#66]
`yqxk@yqxk-virtual-machine:~/work/ibus-rime-master$ sudo ./install.sh 
fatal: Not a git repository (or any of the parent directories): .git
./install.sh: 第 5 行: cd: librime: 没有那个文件或目录
mkdir -p build
(cd build; cmake -DCMAKE_BUILD_TYPE=Release .. && make)
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "FindRime.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Rime", but
  CMake did not find one.

  Could not find a package configuration file provided by "Rime" with any of
  the following names:

    RimeConfig.cmake
    rime-config.cmake

  Add the installation prefix of "Rime" to CMAKE_PREFIX_PATH or set
  "Rime_DIR" to a directory containing one of the above files.  If "Rime"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/yqxk/work/ibus-rime-master/build/CMakeFiles/CMakeOutput.log".
Makefile:14: recipe for target 'ibus-engine-rime' failed
make: *** [ibus-engine-rime] Error 1

`
################
FindRime.cmake这个是什么，

我是新手，想完成手工编译安装，想了解如何编译安装进去而不是sudo apt-get install ibus-rime这样一键的。

ibus版本:1.5.11
ibus-rime:当前git
ubuntu：16.04LTS

感谢。

**Comment by lotem** [comment]
https://github.com/rime/home/wiki/RimeWithIBus#build-and-install-ibus-rime
