### ISSUE TITLE
No weasel.yaml in .config/ibus/rime/build

### ISSUE THREAD

**Issue by Saltychtao** [rime/ibus-rime#67]
Hi, I would like to make the candidate words list in a horizional way,  but it seems that there's no weasel.yaml in my config directory, where can I get the template of weasel.yaml ?

**Comment by zhmars** [comment]
use `ibus_rime.yaml` instead

**Comment by lotem** [comment]
`weasel.yaml` is for https://github.com/rime/weasel

**Comment by lotem** [comment]
try configure the UI in iBus preferences

**Comment by Saltychtao** [comment]
> use `ibus_rime.yaml` instead

I can't find `ibus_rime.yaml` either.


> try configure the UI in iBus preferences

Thanks, I will give it a try.

**Comment by zhmars** [comment]
Correct me if I am wrong,  there is no such template for ibus-rime currently , if you want  a horizional candidate window, you just need to create it yourself and config like what you do in `weasel.yaml`.

Or as lotem suggest, try to config in  iBus preferences if it works for you

**Comment by Saltychtao** [comment]
Thanks, it works.
