### ISSUE TITLE
How to use precompiled dictionary files?

### ISSUE THREAD

**Issue by brglng** [rime/ibus-rime#70]
Hello, I was using a schema created by my own (https://github.com/brglng/rime-xhup), which uses precompiled dictionary, however I cannot get it to work recently. What I did was putting all the `.yaml` and `.bin` files into `~/.config/ibus/rime`. Here is the output I got when I ran `rime_deploy --build`:

```
E0522 20:10:48.197716 20502 dict_compiler.cc:44] source file '/home/zhaosheng/.config/ibus/rime/xhup.dict.yaml' does not exist.
E0522 20:10:48.198226 20502 dict_compiler.cc:96] neither xhup.dict.yaml nor xhup.table.bin exists.
E0522 20:10:48.198240 20502 deployment_tasks.cc:367] dictionary 'xhup' failed to compile.
E0522 20:10:48.205766 20502 deployment_tasks.cc:319] Error updating schema: nonexistent file '/home/zhaosheng/.config/ibus/rime/flypydz.schema.yaml'.
E0522 20:10:48.221563 20502 dict_compiler.cc:44] source file '/home/zhaosheng/.config/ibus/rime/xhup.dict.yaml' does not exist.
E0522 20:10:48.221791 20502 dict_compiler.cc:96] neither xhup.dict.yaml nor xhup.table.bin exists.
E0522 20:10:48.221802 20502 deployment_tasks.cc:367] dictionary 'xhup' failed to compile.
E0522 20:10:48.245286 20502 dict_compiler.cc:44] source file '/home/zhaosheng/.config/ibus/rime/xhup.dict.yaml' does not exist.
E0522 20:10:48.245533 20502 dict_compiler.cc:96] neither xhup.dict.yaml nor xhup.table.bin exists.
E0522 20:10:48.245545 20502 deployment_tasks.cc:367] dictionary 'xhup' failed to compile.
```

**Comment by lotem** [comment]
Keep the source files, not the build binaries.

You can use the exact version of `librime` that was used to create those binary files.
In order to rebuild binary dictionaries, source files (`*.dict.yaml`) are needed.

**Comment by brglng** [comment]
Thank you. However, that would be a problem to me, as the author of 小鹤双拼 does not provide the dictionary publicly now. Maybe I will have to contact him now.

**Comment by nameoverflow** [comment]
> E0522 20:10:48.198226 20502 dict_compiler.cc:96] neither xhup.dict.yaml nor xhup.table.bin exists.

@lotem 如果有 .bin 这条 log 应该不出现的吧？

**Comment by lotem** [comment]
@nameoverflow  `*.bin` 不能做源文件。
如果有 `build/*.bin` 可能行，還得看是否改過格式。

**Comment by nameoverflow** [comment]
@brglng 所以应该把 `*.bin` 文件放到 `build/` 下

**Comment by brglng** [comment]
@nameoverflow 也不行，还是提示错误，估计可能是因为版本不匹配。
