### ISSUE TITLE
Ubuntu 18.04.2 GNOME IBus 1.5.17 選詞錯误

### ISSUE THREAD

**Issue by Zhang-Siyang** [rime/ibus-rime#71]
应该是 小狼毫 才对

![image](https://user-images.githubusercontent.com/22904269/59142456-2907a000-89f1-11e9-90ec-44235198cbe3.png)

luna_pinyin 和 double_pinyin_flypy 都是一样的错误

<details>
<summary>~/.config/ibus/rime/default.yaml</summary>
https://gist.github.com/Zhang-Siyang/7089fc4000cddceb5114706179d970fb <br/>
</details>

**Comment by lee-tts** [comment]
我不是 dev 可是我猜這是雙拼問題，而不是ibus相關問題，可能要再提在這裡：

https://github.com/rime/rime-double-pinyin/issues

**Comment by lotem** [comment]
参考 https://github.com/rime/weasel/issues/164

**Comment by Zhang-Siyang** [comment]
又回到了这台Linux机器上,刚把问题解决,这是我的解决方法:
1. 去往 rime/weasel#164,看到 qijianjun 是这么说的:
```
谢谢，问题解决了。
我用户目录下没有binary文件夹，是在build处理的。
然后比较了重新部署后的yaml文件，只有在luna_pinyin.schema.yaml有新增的几行符号词库有更新，其他是一样的。所以推测可能是之前的bin词库有问题。
```
2. 我不记得哪里是用户目录,去了 ~/.config/ibus/rime 确实看到了几个.bin文件,指向了/usr/share/rime-data之下的几个bin文件
3. 简单翻了翻wiki没有找到哪里是用户目录,大胆把/usr/share/rime-data下的几个bin删了,然后部署,现在可以正常拼词了.

不过现在中文标点都成了西文的(， -> ,),等下我忙完了再看看是哪里的问题
