### ISSUE TITLE
How to customize the yaml file so it only outputs results with single character?

### ISSUE THREAD

**Issue by zilliu** [rime/ibus-rime#72]
I am using Cangjie mode, and I have disabled sentence and completetion under translator, but when I type I still get outputs that contains multiple words as below. Is there any way to customize Rime that it only ouputs results containing single character?
![2019-06-13 21-21-47 的螢幕擷圖](https://user-images.githubusercontent.com/35940720/59477055-83ee2c80-8e21-11e9-8e71-10a9a128af8c.png)

**Comment by lotem** [comment]
You have to use a dictionary that only contains single characters (and do not import phrases).

The `cangjie5` IME offered by Rime Developers use this filter to move all characters to the top of the menu, but it'll still show phrases.
https://github.com/rime/rime-cangjie/blob/master/cangjie5.schema.yaml#L53
