### ISSUE TITLE
rime输入法 对于"进" 这个字后选词中出现为"轻"

### ISSUE THREAD

**Issue by YaoLiMuMu** [rime/ibus-rime#74]
rime输入法 对于"进" 这个字后选词中出现为"轻";
![Screenshot from 2019-07-18 13-55-35](https://user-images.githubusercontent.com/32826811/61432769-fcd22e00-a963-11e9-8898-d5b625484572.png)

**Comment by YaoLiMuMu** [comment]
请问下怎么解决

**Comment by lotem** [comment]
同 https://github.com/rime/ibus-rime/issues/65
