### ISSUE TITLE
加強切換中英模式的可靠度

### ISSUE THREAD

**Issue by lee-tts** [rime/ibus-rime#76]
首先：非常棒的輸入法，感謝

我常遇到的問題是，用《Shift》鍵切換中英模式時，常常失敗，我才是因為我按太快，有其他鍵同時按著的話，ibus 當作是 modifier 而不是換中英的動作。

有什麼辦法讓中英鍵變成 一按就切，像 capslock 一樣，不管同時按什麼按鍵，一定會切換。

用其他按鍵也可以，我不一定要用 Shift

**Comment by lotem** [comment]
不可以實現所求的效果。因爲需要使用Shift和字符按鍵組合輸入上檔字符。
Shift、Control 用來切換狀態，只支持快速單擊該鍵。爲了支持和鼠標組合的動作，長時間按下時也不予切換。
用其他按鍵的話，可以設置爲 CapsLock：
https://github.com/rime/rime-prelude/blob/master/default.yaml#L65
或者添加按鍵綁定：
https://github.com/rime/rime-prelude/blob/master/key_bindings.yaml#L44
