### ISSUE TITLE
No icon in Ubuntu system tray

### ISSUE THREAD

**Issue by whuhacker** [rime/ibus-rime#8]
![screenshot from 2014-09-13 17 27 42](https://cloud.githubusercontent.com/assets/1249600/4260084/57681726-3b28-11e4-8998-b2a3107c379d.png) ibus-libpinyin 
![screenshot from 2014-09-13 17 28 13](https://cloud.githubusercontent.com/assets/1249600/4260085/57796fd0-3b28-11e4-8a7c-922422edd739.png) ibus-rime  

 And double gear icons in ibus panel (`中 <->A` and `Deploy`). Can we use different icons?

**Comment by x-ji** [comment]
@lotem That means we should always download the source code and build the latest version?

**Comment by lotem** [comment]
The latest ibus-rime=1.2 requires librime>=1.0.
Did you mean missing build dependencies of librime?
I've managed to do a static build of ibus-rime on Ubuntu 14.04, building all dependencies except boost from source in librime/thirdparty.
This should work: https://github.com/rime/ibus-rime/blob/master/install-static.sh

**Comment by x-ji** [comment]
I tried to run the file, but now it has the following errors:

```
-- checking for module 'ibus-1.0'
--   package 'ibus-1.0' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:9 (pkg_check_modules)

-- checking for module 'libnotify'
--   package 'libnotify' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:15 (pkg_check_modules)


-- checking for module 'rime'
--   found rime, version 1.2.0
-- Found Rime: /usr/lib/librime.a  
-- Found Brise: /usr/share/rime-data  
-- Precompiler macro RIME_DATA_DIR is set to "/usr/share/rime-data"
-- Configuring incomplete, errors occurred!
See also "/home/jx/ibus-rime/build/CMakeFiles/CMakeOutput.log".
```
Although I have `ibus` and `libnotify-bin` installed among my packages.

Is the installation trying to find an older version of these two packages, or did I not perform some step correctly?

**Comment by lotem** [comment]
@x-ji
In most Linux distros, `ibus`, `libnotify-bin` are *binary* packages, libraries and header files for software development are usually delivered in separate *development* packages, eg. in Ubuntu you need `libibus-1.0-dev`, `libnotify-dev`.
