### ISSUE TITLE
Rime 无法启动

### ISSUE THREAD

**Issue by maghsk** [rime/ibus-rime#80]
Rime 无法启动

症状 1：切换到其他输入引擎（sunpinyin）后，再切换回 Rime 此时依然是 sunpinyin 引擎输入，尽管 ibus 显示已经切换到 Rime 了，实际并未切换回来。
症状 2：切换到 Rime 输入法后，右键 ibus 图标，并未出现“维护”、“同步”等选项。

Archlinux rolling release

**Comment by siriusy** [comment]
同样的问题。

**Comment by siriusy** [comment]
我的再一次更新（-Syu）之后rime恢复正常了。更新记录有一条
upgraded librime (1:1.5.3-1 -> 1:1.5.3-3)

**Comment by maghsk** [comment]
> 我的再一次更新（-Syu）之后rime恢复正常了。更新记录有一条
> upgraded librime (1:1.5.3-1 -> 1:1.5.3-3)

正如 siriusy 所说，更新后已恢复正常。
