### ISSUE TITLE
[BUG] gnome 待上屏词在切换窗口时未清空

### ISSUE THREAD

**Issue by tuberry** [rime/ibus-rime#81]
1. gnome桌面环境选择所有窗口使用相同输入法，在窗口A输入但未上屏时用`Alt+Tab`切换到窗口B，若窗口B存在输入框则候选框会移动到光标位置，否则候选框仍在原处。无论哪种情况输入途中切换窗口都应该视为用户放弃此次输入，保留候选框是不合理的。
截图1:(在gedit1中正在输入)
![Screenshot from 2019-10-19 02-00-33](https://user-images.githubusercontent.com/17917040/67117175-971c6900-f214-11e9-811a-c5d8e52b2d91.png)
截图2:(切换到gedit2窗口，候选框随之移动到2)
![Screenshot from 2019-10-19 02-00-48](https://user-images.githubusercontent.com/17917040/67117229-b9ae8200-f214-11e9-906d-296451cde3ef.png)
截图3:(切换到`tweaks`窗口，候选框在原处不会消失)
![Screenshot from 2019-10-19 02-01-02](https://user-images.githubusercontent.com/17917040/67117284-e5316c80-f214-11e9-8a59-582644662303.png)
2. 以及在未上屏时用鼠标调整窗口位置（不常见的操作），按理说此时已经丢失了输入状态，候选框应该随之消失，但是它仍在原地，并且候选框位置不能通过鼠标调整，须先提交一次才能到正确的位置，在ibus-libpinyin中虽然也不会消失但是继续输入会跳到正确的位置。
截图3:(输入过程中移动窗口)
![Screenshot from 2019-10-19 03-12-57](https://user-images.githubusercontent.com/17917040/67121654-9be61a80-f21e-11e9-9a51-8eb26de22ce7.png)
3. 实际上，即使不是在输入过程中，移动窗口后输入，候选框也只会出现在移动前光标的位置，而不是新的正确的位置。
截图5:(打开gedit后移动窗口再输入，候选框出现在移动前的位置)
![Screenshot from 2019-10-19 03-23-25](https://user-images.githubusercontent.com/17917040/67122301-15cad380-f220-11e9-9a5a-f286cf26cf71.png)
以上三个问题很难说是上游`ibus`的bug，因为在`ibus-libpinyin`中无法复现。
Thanks!

**Comment by AlynxZhou** [comment]
我这仍然存在这个问题，不知道为什么这个bug被关闭了

**Comment by tuberry** [comment]
因为长期无人问津（

**Comment by lotem** [comment]
ibus的這項設計並不完善。輸入法引擎也只好遵循設計。
所有應用窗口的輸入都使用同一個IBusEngine的實例，輸入法引擎無法識別輸入目標窗口和應用，因此以下無法討論多窗口的場景，只能當作針對唯一的輸入目的來處理。
假當是同一個輸入窗口，短暫失去焦點不意味着應用窗口的切換，我對此處清除輸入內容持保守態度。期望用戶通過明確的輸入信號放棄輸入。
試想以下場景：使用gnome-shell，輸入過程中按下Super鍵進入任務視圖，可能只是爲了看一眼疊在下面窗口的內容再繼續寫，或僅僅是誤按了Super鍵。仍回到當前窗口後，能繼續未完成的輸入會是比較可愛的，特別是用語句輸入模式的方案時。
還有一種常見處理是焦點切換時自動提交當前的輸入文字，以免內容丟失。但在嘗試中，我發現Ibus不僅沒有向engine通報輸入目標窗口，僅有有希望的[focus_out](https://github.com/ibus/ibus/blob/2a08af4c979ac42aeb037bb86b7717f4272082b5/src/ibusengine.h#L108)事件其調用的時序也不合適，在此處提交的輸入結果會插入到新窗口的光標處，而不是離開的窗口。在這個地方，僅僅實現清空輸入也許是可行的，但我不願將錯就錯地利用不成熟的接口，實現一個可能對用戶造成更大困擾的操作。
因此在IBus提供更完善的支持之前，我暫不改變現有行爲。

**Comment by tuberry** [comment]
还真的是 feature啊，也不无道理吧。但是我更倾向于失焦就清空内容，原因有两个：
1. 鉴于桌面和应用的零散程度，我对 Ibus 更完善的功能支持不报什么希望。就在 `focus_out` 时处理也挺好。至于同一窗口内失焦，我想到的一个场景是在浏览器输入时用鼠标点击输入框之外的地方但这也应该算放弃输入吧。失焦本身算一种放弃的信号，输入的地方都不再了还保持输入不太合理（按`Super`参看其余窗口输入，我推荐还是分屏毕竟任务视图缩小的窗口字不容易看清
2. 各应用对 `preedit` 部分的处理也不尽相同。拿两个 `Gedit` 窗口来说，切换时原窗口 `preedit` 会被清除，只是输入内容会被另一窗口'继承'（也挺怪的）。但 `chromium` 就不会清除 `preedit` ，于是输入cs后在`gedit` 和 `chromium` 间来回切换就会出现下面的输入。这我也觉着蛮困惑的，不如全清空。
![image](https://user-images.githubusercontent.com/17917040/88945655-d5c17280-d2c0-11ea-9969-12ba09665754.png)
