### ISSUE TITLE
[Feature Request] 在输入光标处显示预编辑字词

### ISSUE THREAD

**Issue by Titubery** [rime/ibus-rime#82]
许多输入法会在用户输入过程中将首选的候选词显示在光标处，这样预输入和已输入的部分更紧密，若正确直接上屏，体验也更好些。
截图1：（ibus-libpinyin输入示意）
![Screenshot from 2019-10-19 02-45-21](https://user-images.githubusercontent.com/17917040/67119951-d3eb5e80-f21a-11e9-9bef-a43b14c746a8.png)
截图2：（ibus-rime输入示意）
![Screenshot from 2019-10-19 02-45-36](https://user-images.githubusercontent.com/17917040/67119983-e4033e00-f21a-11e9-994d-d1936d712d85.png)

**Comment by lotem** [comment]
Already supported this feature:
https://github.com/rime/ibus-rime/blob/5ee34cbfbe31853b333c3399ba5e52c61b84edb5/rime_settings.c#L53
