### ISSUE TITLE
[Feature Request] 类似 Weasel 的预编辑模式

### ISSUE THREAD

**Issue by hosxy** [rime/ibus-rime#83]
希望能增加 windows下小狼毫的预编辑模式，将输入的字符放到预编辑区，如图：
![批注 2019-08-30 112609](https://user-images.githubusercontent.com/17108640/67174407-7f034000-f3f4-11e9-9d5d-e851dce2b15b.png)

ibus-rime现在是这样的：
![2019-10-21_11-08](https://user-images.githubusercontent.com/17108640/67174413-8591b780-f3f4-11e9-8543-4ea23c7820b5.png)

**Comment by nameoverflow** [comment]
……？
这两个有什么区别？

**Comment by hosxy** [comment]
@nameoverflow 简单来说，第一个(Waesel)候选框只有一行,那就是候选字，输入的字符显示在预编辑区域( preedit ? )，Windows10和OSX自带的输入法都是这样
第二个(ibus-rime)候选框有两行，第一行是键入的字符，第二行是候选字，没有预编辑区域(或者预编辑区域不显示任何内容)

**Comment by nameoverflow** [comment]
ibus 本身不支持这种，可以换 fcitx，装 fcitx-rime。

**Comment by hosxy** [comment]
@nameoverflow 首先 ibus 其实是支持这种的，其次fcitx是真不支持这种。之所以觉得ibus不支持这种可能是因为没有一个输入法实现了这种效果，但是其实是支持的。

我在 ibus 那边提过 issue，ibus维护者也说了，这个功能要由具体的输入法来做，因此这个问题就转移到了 ibus-libpinyin 那边，不过 ibus-libpinyin 的维护者不愿意做这个功能，他觉得这样的布局影响用户体验。

**Comment by lotem** [comment]
這個是不是在iBus設置裏可以選。

**Comment by lotem** [comment]
同 https://github.com/rime/ibus-rime/issues/82

**Comment by Titubery** [comment]
#82 通过设置ibus-rime.yaml解决了:
```
 style:
    horizontal: true
    inline_preedit: true
    color_scheme: luna
```
但效果和Mac或Windows不一样，仍然是两行。
![2](https://user-images.githubusercontent.com/17917040/67286308-c03a4380-f50b-11e9-82bd-55f7c076d5ad.png)
另：color_scheme不会改变候选框配色，但影响预编辑区域背景色，能不能去除背景色

**Comment by Titubery** [comment]
@lotem
