### ISSUE TITLE
在Ubuntu使用上突然就不能用“，”和“。”翻页了

### ISSUE THREAD

**Issue by iruletheworld** [rime/ibus-rime#84]
Ubuntu 18.0.4。一直使用正常，今天突然就不能用“，”和“。”翻页了。试了用 `sudo apt-get remove ibus-rime`之后用 `sudo apt-get purge ibus-rime`，然后在重新安装，还是不幸。所有输入法都不能用“，”和“。”翻页

**Comment by iruletheworld** [comment]
重装一下之后发现，如果用 `sudo apt-get install ibus-rime` 下来的话，现在还是好的。但是！如果用东风破更新之后，立即就不能翻页了。

**Comment by lotem** [comment]
抱歉，最新的配置需要librime 版本1.4以上才能支持。

**Comment by iruletheworld** [comment]
> 抱歉，最新的配置需要librime 版本1.4以上才能支持。

请问要怎样才能更新librim的版本？

**Comment by hamkido** [comment]
@iruletheworld debian buster 源里面librime-bin 版本号已经是 1.4.0+dfsg1-2+b1
ubuntu源里面应当也更新了
或者你可以自己编译一份

**Comment by lotem** [comment]
舊版本的輸入法程序無法支持新的配置。
鑑於問題並非出在Ubuntu包好的數據包，本題關閉。
