### ISSUE TITLE
在GNOME-Shell+IBus下中州韵无法用鼠标选词

### ISSUE THREAD

**Issue by Icenowy** [rime/ibus-rime#9]
ibus-pinyin, ibus-anthy就可以。。。
（而且还不能显示翻页按钮（这一点ibus-pinyin都不行，只有ibus-anthy可以））

**Comment by osfans** [comment]
翻頁按鈕做好了，沿用了你的回調函數。請幫忙測試： 42e051a52235f0a2f7813aeda0833a12b1d103d0

**Comment by Icenowy** [comment]
OK Perfect. Thanks a lot.

- 发送自我的Sony Xperia™智能手机

---- Osfans编写 ----

翻頁按鈕做好了，沿用了你的回調函數。請幫忙測試： 42e051a52235f0a2f7813aeda0833a12b1d103d0

---

**Comment by Icenowy** [comment]
一个小bug：最后一页翻页按钮会消失

- 发送自我的Sony Xperia™智能手机

---- Osfans编写 ----

翻頁按鈕做好了，沿用了你的回調函數。請幫忙測試： 42e051a52235f0a2f7813aeda0833a12b1d103d0

---

**Comment by osfans** [comment]
好像有難度了，librime默認只取出一頁。
沒辦法翻到第二頁，所以不能搞出只有page up的情況。
倒是可以做出最後一頁同時有page up/down按鈕。

**Comment by Icenowy** [comment]
不过第一页有一个按钮可用，第二页到倒数第二页有两个按钮，最后一页没有，这是现状。。。所以我觉得只要判断没有按钮就加上个pageup？

- 发送自我的Sony Xperia™智能手机

---- Osfans编写 ----

好像有難度了，librime默認只取出一頁。
沒辦法翻到第二頁，所以不能搞出只有page up的情況。
倒是可以做出最後一頁同時有page up/down按鈕。

---

**Comment by osfans** [comment]
page up那個按鍵是循環翻頁，要有兩頁的時候才出現。
前面的頁面我都是在後面加了一個空字符串，僞造成兩頁。
最後一頁沒有加空字符串，所以就不出現了。

**Comment by Icenowy** [comment]
机智得我都佩服了。。。最后一页那就做显示两个按钮吧

- 发送自我的Sony Xperia™智能手机

---- Osfans编写 ----

page up那個按鍵是循環翻頁，要有兩頁的時候才出現。
前面的頁面我都是在後面加了一個空字符串，僞造成兩頁。
最後一頁沒有加空字符串，所以就不出現了。

---

**Comment by osfans** [comment]
目前只能這樣了，第一頁page up不可用，其餘頁兩個按鈕可用。
做好了：a03f42e89ba085b10189ce0ebc8206c6cda0e1f0

TODO: 最後一頁page down應該不可用。

**Comment by osfans** [comment]
找到翻到第二頁的方法了，現在最後一頁也沒問題了： 3d71cb5f58f370cf2076c570a4874aeb9f12888f

**Comment by Icenowy** [comment]
非常不错。十分感谢。

- 发送自我的Sony Xperia™智能手机

---- Osfans编写 ----

找到翻到第二頁的方法了，現在最後一頁也沒問題了： 3d71cb5f58f370cf2076c570a4874aeb9f12888f

---
