### ISSUE TITLE
Patch to fixes ibus-rime compile with gcc 10

### ISSUE THREAD

**Issue by epico** [rime/ibus-rime#90]
ibus-rime 1.4.0 FTBFS in Fedora rawhide/32.

Here are the patch to fix compile:
https://src.fedoraproject.org/rpms/ibus-rime/blob/master/f/ibus-rime-1.4.0-fixes-compile.patch

URL: https://bugzilla.redhat.com/show_bug.cgi?id=1799518

**Comment by lotem** [comment]
Thanks. Patch applied to HEAD.

**Comment by epico** [comment]
Thanks for the quick review!
