### ISSUE TITLE
Mint上候选栏消失

### ISSUE THREAD

**Issue by thep0y** [rime/ibus-rime#92]
能正常输入文字，任务栏有输入法图标，但没有候选栏。试过killall ibus-daemon并ibus-daemon -x -r -d无效。
![image](https://user-images.githubusercontent.com/51874567/75498983-9cc85d80-5a03-11ea-9478-80ea8838a7ff.png)

**Comment by Edenharder** [comment]
Same problem with Manjaro 21.1.1. The problem might be related to  [Candidate panel goes off screen](https://github.com/ibus/ibus/issues/2075).

**Comment by nosayx** [comment]
Arch Linux   + 1

**Comment by lotem** [comment]
Please report UI bugs to https://github.com/ibus/ibus/issues

**Comment by alligatorme** [comment]
Manjaro+1, just happen in firefox,others are OK

**Comment by Edenharder** [comment]
This problem has already been solved in Archlinux. Manjaro hopefully soon.
