### ISSUE TITLE
如何在centos8上安装

### ISSUE THREAD

**Issue by runmain** [rime/ibus-rime#95]

**Comment by byujiang** [comment]
直接 Clone，然后 直接 运行 install.sh 就行。最好修改 install.sh, 在
```
git submodule update --init
```
后加上
```
cd librime && git checkout master && cd ..
cd plum && git checkout master && cd ..
```
默认的不是最新的 commit

**Comment by kawav** [comment]
centos 8 [is base on fedora 28](https://docs.fedoraproject.org/en-US/quick-docs/fedora-and-red-hat-enterprise-linux/index.html), also you can try to `rpm -ivh` the fedora 28 or older version of [ibus-rime](https://koji.fedoraproject.org/koji/packageinfo?packageID=16229).

**Comment by runmain** [comment]
> 直接 Clone，然后 直接 运行 install.sh 就行。最好修改 install.sh, 在
> 
> ```
> git submodule update --init
> ```
> 
> 后加上
> 
> ```
> cd librime && git checkout master && cd ..
> cd plum && git checkout master && cd ..
> ```
> 
> 默认的不是最新的 commit

**Comment by runmain** [comment]
> 直接 Clone，然后 直接 运行 install.sh 就行。最好修改 install.sh, 在
> 
> ```
> git submodule update --init
> ```
> 
> 后加上
> 
> ```
> cd librime && git checkout master && cd ..
> cd plum && git checkout master && cd ..
> ```
> 
> 默认的不是最新的 commit

好多依赖都不兼容，几经曲折，还是装上了

**Comment by runmain** [comment]
> centos 8 [is base on fedora 28](https://docs.fedoraproject.org/en-US/quick-docs/fedora-and-red-hat-enterprise-linux/index.html), maybe you can try to `rpm -ivh` the fedora 28 or older version of [ibus-rime](https://koji.fedoraproject.org/koji/packageinfo?packageID=16229) (but it is not work for me).

```
sudo dnf install -y gcc gcc-c++ boost boost-devel cmake make cmake3
sudo dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/marisa-0.2.4-4.el7.x86_64.rpm -y
sudo dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/marisa-devel-0.2.4-4.el7.x86_64.rpm -y 
sudo dnf install https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/k/kyotocabinet-libs-1.2.77-1.el7.x86_64.rpm -y
sudo dnf install https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/k/kyotocabinet-1.2.77-1.el7.x86_64.rpm -y
sudo dnf --enablerepo=PowerTools  install glog glog-devel  yaml-cpp yaml-cpp-devel gtest gtest-devel libnotify zlib zlib-devel gflags gflags-devel leveldb leveldb-devel libnotify-devel ibus-devel  -y


# for OpenCC
sudo dnf --enablerepo=PowerTools install doxygen -y
sudo curl -L https://github.com/BYVoid/OpenCC/archive/ver.1.0.6.tar.gz | sudo  tar zx
cd OpenCC-ver.1.0.6/
sudo make
sudo make install 
sudo ln -s /usr/lib/libopencc.so /usr/lib64/libopencc.so
cd /usr/src
# git download 
sudo git clone https://github.com/rime/ibus-rime.git 
cd ibus-rime/
sudo git submodule update --init
# install again
sudo dnf install http://mirror.centos.org/centos/7/os/x86_64/Packages/marisa-devel-0.2.4-4.el7.x86_64.rpm -y 
sudo ./install.sh

#if
# ldd /usr/lib/ibus-rime/ibus-engine-rime
#  >librime.so.1 => not found
#  >libopencc.so.2 => not found
#then 

# ln -s /usr/lib/librime.so.1.4.0 /usr/lib64/librime.so.1
# ln -s /usr/lib/libopencc.so.1.0.0 /usr/lib64/libopencc.so.2

```

**Comment by inoton** [comment]
> > centos 8 [is base on fedora 28](https://docs.fedoraproject.org/en-US/quick-docs/fedora-and-red-hat-enterprise-
.....
> ```

按照步骤装完，就是不能使用。

**Comment by inoton** [comment]
> _No description provided._

按照骤顺利装完，就是不能使用。
输入法可以调出来，右上角 输入法切换器 中，显示中文输入法的图标是一个“Ｗ”；
同时$Home/.config/ibus/rim/没法生成 输入法码表和配置信息。

**Comment by runmain** [comment]
是不是有的依赖装的版本太高了比如：marisa 这个不能太高

**Comment by inoton** [comment]
> marisa
之前是按你的步骤照抄的。
现在在用小小输入法了，这个安装太麻烦了。
Fedora下安装ibus-rime就一条命令搞定，CentOS安装了300多兆的东西末了还不能用。

**Comment by syaoo** [comment]
感觉CentOS软件仓库的资源太少了Orz
