### ISSUE TITLE
ibus-rime不支持app_options吗？

### ISSUE THREAD

**Issue by OdinZhang** [rime/ibus-rime#96]
我想在ibus-rime 上实现鼠须管和小狼毫都有的app_options选项，但是没有成功，是因为根本就不支持吗？还是我操作不对？

**Comment by lotem** [comment]
不支持。

**Comment by tuberry** [comment]
如果是 Gnome 的话试试[IBus-Tweaker](https://extensions.gnome.org/extension/2820/ibus-tweaker/)

**Comment by amorphobia** [comment]
@lotem 请问将来也没有支持的计划吗？

**Comment by lotem** [comment]
未來的事，無法預知。
目前沒有這項開發計劃。

**Comment by amorphobia** [comment]
@lotem 
感谢回复。
