### ISSUE TITLE
添加删除快捷键

### ISSUE THREAD

**Issue by wi24rd** [rime/ibus-rime#97]
类似使用 readline 库的程序比如 bash 的键绑定，
c-k 删除光标后的所有输入，c-u 删除光标前的所有输入，c-w 删除词组开头到光标间的输入（这个可以放最后考虑，很容易和比如浏览器之类的冲突），等等。

**Comment by lotem** [comment]
這些是指對輸入法緩衝區的操作還是對應用程序中文本的操作？
如果是後者，輸入法是不支持這些操作的。大多數的shell程序內置了這些快捷鍵，你也可以在系統級別設置用Emacs風格的編輯鍵。

**Comment by wi24rd** [comment]
当然是前者

**Comment by lotem** [comment]
不太明白「词组开头到光标间的输入」怎樣界定，以及爲什麼會和瀏覽器衝突。

**Comment by lotem** [comment]
從光標處刪到開頭和刪到結尾，這兩種操作目前Rime的程序裏都沒有實現，在中文輸入法裏我也見過這樣的先例。估計是使用場景較少的原因。

輸入法光標大多數時候在末尾，這時已經有一個用戶比較常用的操作，即清除全部未選定的輸入內容，這基本覆蓋了大多數「刪到開頭」的使用場景。我考慮非整句輸入風格的輸入法裏面，用戶的輸入一般不長，移動光標編輯輸入串的本身就比較少，而只有在光標移動到長輸入串中間的情況，纔有機會用到刪到開頭和刪到結尾，所以大多數的輸入法都沒有設置這些操作。本品沒有照搬編輯器的全套文本編輯操作，而是拿來適應輸入法的動作集合，其中<kbd>C-k</kbd>已經挪用給了刪除選中詞條，和所求有一點衝突。

總之我覺得這兩個需求不強。另外一個<kbd>C-w</kbd>還不太明確，中文不像命令行那樣有清晰的「詞」邊界，但他基本上會和「清除輸入」和「刪到開頭」的使用場景高度重合。總體感覺是不能照搬命令行上的操作到輸入法裏來。

**Comment by wi24rd** [comment]
c-w 那个我说的其实是中文的字，就是 rime
在输入的时候他会把输入的字符按字用空格分组，就是说删除光标所指的这个字开头的空格到光标间的所有字符内容。冲突这个是因为我也不清楚具体机制怎么样，ibus
在输入的时候浏览器会不会也把这个事件给捕捉，只是猜测有可能存在这个问题。

**Comment by wi24rd** [comment]
BTW，GNOME 设成 Emacs keybing 对 ibus 看起来无效。
