### ISSUE TITLE
在 i3-wm 上使用rime，输入的提示窗口只能在主屏幕

### ISSUE THREAD

**Issue by sprhawk** [rime/ibus-rime#99]
系统：Debian 10
i3: 4.16.1-1
i3-gnome:  24a56b827461a3ebac96814032fa43c425c9455a 
gnome: 3.30.0

双显示器配置，在一个显示器底部显示控制条（蓝牙，声音，输入法等控制图标），称之为主屏幕，这时在另一个屏幕上输入中文，输入提示/侯选框显示在主屏幕上。但是Super + Space 切换输入法的功能在主屏幕上

**Comment by lotem** [comment]
界面由 [ibus](https://github.com/ibus/ibus) 實現。
